# Database ba?lant?s?
spring.datasource.url=jdbc:postgresql://localhost:5432/dbblogdev
spring.datasource.username=postgres
spring.datasource.password=sahin275404
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port (iste?e ba?l?)
server.port=8080

blog.app.jwtSecret=MySuperSecretKey
blog.app.jwtExpirationMs=86400000